apiVersion: v1
kind: Service
metadata:
  name: sap-lab
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: sap-lab
    app.kubernetes.io/instance: {{ .Release.Name }}-sap-lab
  sessionAffinity: None
  type: ClusterIP
