apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sap-lab-pvc
spec:
  storageClassName: {{ .Values.pv.class }}
  accessModes:
    - {{ .Values.pv.accessmode }}
  resources:
      requests:
        storage: 3Mi
  selector:
    matchLabels:
      qname: {{ .Values.pv.name }}

